### ISSUE TITLE
problem downoading soccerdata package

### ISSUE THREAD

**Issue by spiros26** [probberechts/soccerdata#152]
outputs something like that:

Collecting soccerdata
  Using cached soccerdata-1.3.3-py3-none-any.whl (37 kB)
Collecting flake8-rst-docstrings<0.4.0,>=0.3.0
  Using cached flake8_rst_docstrings-0.3.0-py3-none-any.whl (10 kB)
Requirement already satisfied: PySocks<2.0.0,>=1.7.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from soccerdata) (1.7.1)
Collecting flake8-docstrings<2.0.0,>=1.6.0
  Using cached flake8_docstrings-1.6.0-py2.py3-none-any.whl (5.7 kB)
Requirement already satisfied: selenium<5.0.0,>=4.0.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from soccerdata) 
(4.8.0)
Requirement already satisfied: pandas<2.0,>=1.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from soccerdata) (1.2.3)
Requirement already satisfied: unicode<3.0,>=2.7 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from soccerdata) (2.9)Requirement already satisfied: Unidecode<2.0.0,>=1.2.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from soccerdata) (1.3.6)
Requirement already satisfied: lxml<5.0,>=4.6 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from soccerdata) (4.9.1)
Collecting rich<14.0.0,>=13.0.0
  Using cached rich-13.2.0-py3-none-any.whl (238 kB)
Requirement already satisfied: requests<3.0,>=2.23 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from soccerdata) (2.25.1)
Collecting pretty-errors<2.0.0,>=1.2.25
  Using cached pretty_errors-1.2.25-py3-none-any.whl (17 kB)
Collecting undetected-chromedriver<4.0.0,>=3.1.3
  Using cached undetected-chromedriver-3.2.1.tar.gz (60 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-gd_1b_3_\\undetected-chromedriver_d7b12b0c149841a69a822e4f97be4d81\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-gd_1b_3_\\undetected-chromedriver_d7b12b0c149841a69a822e4f97be4d81\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-i3p4ojhx'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-gd_1b_3_\undetected-chromedriver_d7b12b0c149841a69a822e4f97be4d81\
    Complete output (28 lines):
    Traceback (most recent call last):
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2851, in get_entry_map        
        ep_map = self._ep_map
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2813, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-gd_1b_3_\undetected-chromedriver_d7b12b0c149841a69a822e4f97be4d81\setup.py", line 38, in 
<module>
        setup(
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 142, in _install_setup_requires  
        dist = MinimalDistribution(attrs)
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 134, in __init__
        distutils.core.Distribution.__init__(self, filtered)
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 432, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 641, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2853, in get_entry_map        
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2538, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/39/28/78b39039d3dc2b01d3c9e0b3b51d107878f64f6844aa9f5d970e4ae4a6c7/undetected-chromedriver-3.2.1.tar.gz#sha256=3fe5b6e75b7170efa2f4c53e74bc68ba01d62a30c1a2a5773227fbdd9717d1d8 (from https://pypi.org/simple/undetected-chromedriver/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading undetected-chromedriver-3.2.0.tar.gz (59 kB)
     |████████████████████████████████| 59 kB 948 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-gd_1b_3_\\undetected-chromedriver_e3ef5533e9dd4b57a1c6cc49b8da448f\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-gd_1b_3_\\undetected-chromedriver_e3ef5533e9dd4b57a1c6cc49b8da448f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-ewulx1to'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-gd_1b_3_\undetected-chromedriver_e3ef5533e9dd4b57a1c6cc49b8da448f\
    Complete output (28 lines):
    Traceback (most recent call last):
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2851, in get_entry_map        
        ep_map = self._ep_map
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2813, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-gd_1b_3_\undetected-chromedriver_e3ef5533e9dd4b57a1c6cc49b8da448f\setup.py", line 38, in 
<module>
        setup(
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 142, in _install_setup_requires  
        dist = MinimalDistribution(attrs)
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 134, in __init__
        distutils.core.Distribution.__init__(self, filtered)
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 432, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 641, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2853, in get_entry_map        
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2538, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------

**Comment by probberechts** [comment]
See https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/408 and https://stackoverflow.com/questions/17985110/errors-while-installing-python-packages

I am closing this as this is not related to the soccerdata package, but rather a problem with your Python installation.
