### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by IvenSchloesser** [probberechts/soccerdata#600]
Hey guys,
can you help me, I don't know what I am doing wrong:
Just want to test the scaper.

import soccerdata as sd

fbref = sd.FBref()

player_season_stats = fbref.read_player_season_stats(stat_type="standard")

leagues = fbref.available_leagues()

print(leagues)

Output:

[Running] python -u "-\soccerdata-1.7.1\test.py"
Traceback (most recent call last):
  File "-\soccerdata-1.7.1\test.py", line 1, in <module>
    import soccerdata as sd
  File "-\soccerdata\__init__.py", line 18, in <module>
    from .clubelo import ClubElo
  File "-\soccerdata\clubelo.py", line 11, in <module>
    from ._common import BaseRequestsReader, standardize_colnames
  File "-\soccerdata\_common.py", line 18, in <module>
    import undetected_chromedriver as uc
  File "C:\Users\-\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 44, in <module>
    from .patcher import IS_POSIX
  File "C:\Users\-\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 4, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

**Comment by IvenSchloesser** [comment]
pip install setuptools

**Comment by IvenSchloesser** [comment]
pip install setuptools
